services:
    ethereum-api:
        build:
            context: ./docker
            dockerfile: Dockerfile
            args:
                APP_ENV: '${APP_ENV:-local}'
                NODE_VERSION: '${NODE_VERSION:-16}'
        image: ethereum/ethereum-api
        pull_policy: never
        restart: unless-stopped
        environment:
            HOST_UID: '${HOST_UID:-1000}'
            HOST_GID: '${HOST_GID:-1000}'
            ETHEREUM_MONGODB_URL: '${MONGODB_URL:-mongodb://$DB_USERNAME:$DB_PASSWORD@mongo:27017}'
            ETHEREUM_MONGODB_NAME: 'ethereum-api'
            ETHEREUM_WS: '${ETHEREUM_WS}'
            ETHEREUM_STORAGE_PATH: '${ETHEREUM_STORAGE_PATH:-/home/node/app/storage}'
            ETHEREUM_KEYPATH: '${ETHEREUM_KEYPATH}'
            ETHEREUM_CRTPATH: '${ETHEREUM_CRTPATH}'
            ETHEREUM_LOGFILE: '${ETHEREUM_LOGFILE}'
            ETHEREUM_BIND: '${ETHEREUM_BIND:-localhost}'
            ETHEREUM_PORT: '${ETHEREUM_PORT:-8000}'
        volumes:
            -   type: bind
                source: '.'
                target: '/home/node/app'
            -   type: bind
                source: '${HOME}/.npm'
                target: '/tmp/.npm'
        networks:
            - wallets
        ports:
          - '8000:8000'
        healthcheck:
            test: [ "CMD-SHELL", "curl --fail http://localhost:8000/ping || exit 1" ]
            start_period: 2m

networks:
    wallets:
        driver: bridge
